apiVersion: apps/v1
kind: Deployment
metadata:
  name: costomer-center
  labels:
    app: costomer-center
spec:
  replicas: 1
  selector:
    matchLabels:
      app: costomer-center
  template:
    metadata:
      labels:
        app: costomer-center
    spec:
      containers:
        - name: costomer-center
          image: username/costomer-center:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
